---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roadmap-cm
data:
  nacos.server.host: "10.101.131.126"
  nacos.server.port: "8848"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roadmap-java
  name: roadmap-java
  namespace: default
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: roadmap-java
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: roadmap-java
    spec:
      containers:
        - image: ${ROADMAP_JAVA_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: roadmap-java
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NACOS_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: nacos.server.host
            - name: NACOS_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: nacos.server.port
                  #      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-java-svc
  labels:
    app: roadmap-java-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - name: port
      port: 40012
      protocol: TCP
      targetPort: 8080
  selector:
    app: roadmap-java
  sessionAffinity: None
