---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roadmap-cm
  namespace: default
data:
  nacos.server.host: "${NACOS_SERVER_HOST}"
  nacos.server.port: "${NACOS_SERVER_PORT}"
  database.url: "${DATABASE_URL}"
  database.username: "${DATABASE_USERNAME}"
  database.password: "${DATABASE_PASSWORD}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roadmap-java
  name: roadmap-java
  namespace: default
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: roadmap-java
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: roadmap-java
    spec:
      containers:
        - image: ${ROADMAP_JAVA_IMAGE_URL}
          imagePullPolicy: IfNotPresent
          name: roadmap-java
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NACOS_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: nacos.server.host
            - name: NACOS_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: nacos.server.port
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: database.url
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: roadmap-cm
                  key: database.passowrd
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-java-svc
  labels:
    app: roadmap-java-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 40012
      protocol: TCP
      targetPort: 8080
  selector:
    app: roadmap-java
  sessionAffinity: None
