apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roadmap-java
  name: roadmap-java
  namespace: default
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: roadmap-java
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: roadmap-java
    spec:
      containers:
        - image: ${ROADMAP_JAVA_IMAGE_TAG}
          imagePullPolicy: Always
          name: roadmap-java
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-java-svc
  namespace: default
spec:
  ports:
    - name: port
      port: 40002
      protocol: TCP
      targetPort: 8080
  selector:
    app: roadmap-java
  sessionAffinity: None
  type: ClusterIP


