
gitlab:
  project_id: "92"
  project_name: "roadmap"
  url: "https://code.mantas.cn"
  access_token: "n6tZkTgB6q5Vc3RKyy-S"

spring:
  cache:
    cache-names: "tapd-roles, tapd-users"
    type: simple

nacos:
  config:
    tapdx:
      server_addr: "172.31.13.180:8848"
      namespace: "17013706-c074-4416-af54-b002b34157a2"
      data_id: "tapdx"
      group_id: "projects"

server:
  port: 8080
