

spring:
  cache:
    cache-names: "tapd-roles, tapd-users"
    type: simple
# jackson的配置查看: GlobalConfiguration::jsonCustomizer()
#  jackson:
#    deserialization:
#      fail-on-unknown-properties: false
#    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: "jdbc:mysql://food-dev.mysql.polardb.rds.aliyuncs.com:3306/roadmap"
    username: "roadmap"
    password: "roadmap_123"
    driver-class-name=: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 5
      min-idle: 1
      filter:
        slf4j:
          enabled: true

nacos:
  config:
    tapdx:
      module: "tapdx"
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_TAPDX_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_TAPDX_DATA_ID:tapdx}
      group_id: ${NACOS_TAPDX_GROUP_ID:roadmap}
    roadmap:
      module: "roadmap"
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_ROADMAP_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_ROADMAP_DATA_ID:gitlab}
      group_id: ${NACOS_ROADMAP_GROUP_ID:roadmap}
    alilog:
      module: "alilog"
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_ALILOG_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_ALILOG_DATA_ID:alilog}
      group_id: ${NACOS_ALILOG_GROUP_ID:roadmap}
    dingtalk:
      module: "dingtalk"
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_DINGTALK_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_DINGTALK_DATA_ID:dingtalk}
      group_id: ${NACOS_DINGTALK_GROUP_ID:roadmap}


server:
  port: 8080

logging:
  level:
    root: info
    com:
      mantas: debug
    org:
      springframework:
        security: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n"

