

spring:
  cache:
    cache-names: "tapd-roles, tapd-users"
    type: simple
# jackson的配置查看: GlobalConfiguration::jsonCustomizer()
#  jackson:
#    deserialization:
#      fail-on-unknown-properties: false
#    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: "jdbc:mysql://food-dev.mysql.polardb.rds.aliyuncs.com:3306/roadmap"
    username: "roadmap"
    password: "roadmap_123"
    driver-class-name=: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 5
      min-idle: 1
      filter:
        slf4j:
          enabled: true
#          statement-create-after-log-enabled: false
#          statement-log-enabled: false
#          statement-executable-sql-log-enable: true
#          statement-log-error-enabled: true
#          result-set-log-enabled: false
#  security:
#    oauth2:
#      client:
#        registration:
#          dingtalk:
#            client-id: ""
#            client-secret: ""
#        provider:
#          dingtalk:
#            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
#            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
#            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
#            user-name-attribute: sub
#          jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
#auth:
#  dingtalk:
#    callback-uri: "/api/auth/dingtalk/callback"
#    client-id: "dinght8oiuzenkv4twpc"
#    client-secret: "V0sA_s3zXXJljqMItO9mprkyGYlQ82ONiOtX1RIE5ZdnI5Anw_2U23BWOMNMVcQt"
#    grant-type: "authorization_code"
#    corp-id: "ding5658ef4fd884174f35c2f4657eb6378f"
#    authentication-callback-url: "/api/auth/dingtalk/callback"


nacos:
  config:
    tapdx:
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_TAPDX_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_TAPDX_DATA_ID:tapdx}
      group_id: ${NACOS_TAPDX_GROUP_ID:roadmap}
    roadmap:
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_ROADMAP_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_ROADMAP_DATA_ID:gitlab}
      group_id: ${NACOS_ROADMAP_GROUP_ID:roadmap}
    alilog:
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_ALILOG_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_ALILOG_DATA_ID:alilog}
      group_id: ${NACOS_ALILOG_GROUP_ID:roadmap}
    dingtalk:
      server_addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
      namespace: ${NACOS_ALILOG_NAMESPACE:17013706-c074-4416-af54-b002b34157a2}
      data_id: ${NACOS_ALILOG_DATA_ID:dingtalk}
      group_id: ${NACOS_ALILOG_GROUP_ID:roadmap}


server:
  port: 8080

logging:
  level:
    root: info
    com:
      mantas: debug
    org:
      springframework:
        security: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n"

